Repository Atrolabs/We-Go-Jim, pull requests merged in 2023-11, with the labels that each got.

#18 Added routes to view the login and registration pages
  .gitignore
  app/__init__.py
  app/routes.py
  app/templates/index.html
  run.py
Labels: enhancement, backend

#25 24 login and register templates should not extend index.html
  app/templates/login.html
  app/templates/register.html
Labels: enhancement

#48 Login and reg redirect
  app/static/css/login.css
  app/static/css/register.css
  app/static/js/login.js
  app/static/js/register.js
  app/templates/login.html
  app/templates/register.html
Labels: enhancement, frontend
