Repository Atrolabs/We-Go-Jim, pull requests merged in 2023-12, with the labels that each got.

#54 53 s3 fix
  app/routes.py
  config/.env.example
  config/config_loader.py
  debug/test.json
  services/__init__.py
  services/s3_service.py
Labels: bug

#57 Feature/add workout form, add option to showing workouts
  app/__init__.py
  app/routes.py
  app/static/css/add_workout.css
  app/static/css/my_workouts.css
  app/static/js/add_workout.js
  app/templates/add_workout.html
  app/templates/my_workouts.html
  models/models.py
  services/s3_service.py
Labels: enhancement

#63 Feature/62 navbar
  app/routes.py
  app/static/css/add_workout.css
  app/static/css/dashboard.css
  app/static/css/my_workouts.css
  app/static/css/navbar.css
  app/static/js/navbar.js
  app/templates/add_workout.html
  app/templates/dashboard.html
  app/templates/my_workouts.html
  app/templates/navbar.html
Labels: fix

#64 First release
  .gitignore
  LICENSE
  README.md
  app/__init__.py
  app/routes.py
  app/static/css/add_workout.css
  app/static/css/dashboard.css
  app/static/css/login.css
  app/static/css/my_workouts.css
  app/static/css/navbar.css
  app/static/css/register.css
  app/static/img/Logo_we_go_jim1.png
  app/static/img/Logo_we_go_jim_2.png
  app/static/js/add_workout.js
  app/static/js/login.js
  app/static/js/navbar.js
  app/static/js/register.js
  app/templates/add_workout.html
  app/templates/dashboard.html
  app/templates/login.html
  app/templates/my_workouts.html
  app/templates/navbar.html
  app/templates/not_allowed.html
  app/templates/register.html
  config/.env.example
  config/config_loader.py
  debug/add_workout_debug.sh
  debug/test.json
  misc/We_Go_Jim.mm
  models/__init__.py
  models/models.py
  requirements.txt
  run.py
  screens/add_workout_js_constructWorkoutPlan.png
  scripts/delete_unconfirmed.sh
  services/__init__.py
  services/cognito_service.py
  services/s3_service.py
  terraform/.terraform.lock.hcl
  terraform/cognito.tf
  terraform/outputs.tf
  utils/__init__.py
  utils/cognito_utils.py
  utils/logs_utils.py
Labels: release
